### ISSUE TITLE
Add support for if/else block

### ISSUE THREAD

**Issue by vanmash** [qetza/replacetokens-task#40]
Can `replacetokens-task` support if/else block?

it would be useful for helm's `values.yaml` file

reference:
https://helm.sh/docs/chart_template_guide/control_structures/#ifelse

**Comment by qetza** [comment]
Hi @vanmash,
Thanks for the suggestion but the goal of my task is to do a simple find and replace with as less process as possible.

Adding support for if/else would need to define a grammar, have a parser and runtime code execution which would complexify the code and increase the risk of execution error.

My recommendation if you want conditional support would be to do this through scripting by either dynamically updating the file structure or dynamically generating variable values.
