### ISSUE TITLE
Testing replacement token test on simple yaml file with MS agent

### ISSUE THREAD

**Issue by soundd2** [qetza/replacetokens-task#45]
I have done Testing “replacement token” test on simple yaml file with MS agent. which is YAML below: I have used MS agent

all tasks succeeded but not sure why it is not replaced and showing as test02  it is in last task which “print after file replace”

YAML file:

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: TestSetting
  default: testSet01
  values:
  - testSet01
  - testSet02
  - testSet03

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - task: Bash@3
      displayName: 'Set variable'
      inputs:
        targetType: inline
        script: |
          echo 'The selected TestSetting is ${{ parameters. TestSetting }}.'
          echo "##vso[task.setvariable variable=TestSettings_Name;] ${{ parameters. TestSetting }}"

- task: Bash@3
      displayName: 'Print file before replace'
      inputs:
        targetType: inline
        script: 'cat $(System.DefaultWorkingDirectory)/appsettings.json'
    
- task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'echo $(TestSetting_Name)'

- task: Bash@3
      inputs:
          targetType: 'inline'
          script: 'cat $(System.DefaultWorkingDirectory)/appsettings.json'

- task: replacetokens@6
      inputs:
        root: '$(System.DefaultWorkingDirectory)'
        sources: 'appsettings.json'
    
- task: Bash@3
      displayName: 'Print file after replace'
      inputs:
        targetType: inline
        script: 'cat $(System.DefaultWorkingDirectory)/appsettings.json'

File from code where it has to replace:

![image](https://github.com/qetza/replacetokens-task/assets/94822959/f87cd8ca-7aae-4d6e-a150-e7c930377034)

Logs:

[logs_1346.zip](https://github.com/user-attachments/files/16126376/logs_1346.zip)

Please suugest

**Comment by qetza** [comment]
Hi @soundd2,
Based on your screenshot you are using the syntax `{{ ... }}` to mark your token in your file. This is not the default pattern of the task. You have 2 options:

1. keep you current syntax and configure the task to use this pattern:
  ```yaml
  - task: replacetokens@6
    inputs:
      root: '$(System.DefaultWorkingDirectory)'
      sources: 'appsettings.json'
      tokenPattern: doublebraces
  ```
2. use the default task pattern in you file:
  ```xml
  <?xml version="1.0" encoding="UTF-8"?>
  <TestSettings name="#{ TestSettings_Name }#">
  //...
  </TestSettings>
  ```

**Comment by soundd2** [comment]
Thank you , it worked
