### ISSUE TITLE
Access outputs documentation has invalid syntax

### ISSUE THREAD

**Issue by finkinfridom** [qetza/replacetokens-task#47]
In the readme (and also the documentation into the Visual Studio Marketplace), there is this code sample

```
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@6
  name: replace-tokens
  inputs:
    sources: '**/*.json'
- script: |
    echo "defaults  : $(replace-tokens.defaults }}"
    echo "files     : $(replace-tokens.files }}"
    echo "replaced  : $(replace-tokens.replaced }}"
    echo "tokens    : $(replace-tokens.tokens }}"
    echo "transforms: $(replace-tokens.transforms }}"
```

unfortunately, the `name` propery has an invalid syntax (the `-` char is not allowed) and the script with the `echo` statements contains `$(` opening braces but endings with `}}` which is invalid.

Thanks

**Comment by finkinfridom** [comment]
Moreover, no matter which `echo` statement I try to use but I always receive this error

<img width="415" alt="image" src="https://github.com/user-attachments/assets/720aa4d1-be1e-499e-83b4-457c990e5d43">

any suggestions?

**Comment by finkinfridom** [comment]
this should be the working version

```
- task: qetza.replacetokens.replacetokens-task.replacetokens@6
    displayName: replace tokens in tf and tfvars files
    name: replacetokens
    inputs:
      sources: "**/*json"

  - script: |
      echo 'defaults  : $(replacetokens.defaults)'
      echo 'files     : $(replacetokens.files)'
      echo 'replaced  : $(replacetokens.replaced)'
      echo 'tokens    : $(replacetokens.tokens)'
      echo 'transforms: $(replacetokens.transforms)'
    displayName: "DEBUG replace tokens in tf and tfvars files"
```

**Comment by qetza** [comment]
Hi @finkinfridom,
Thanks for raising the issue, documentation is now fixed :smile:
