### ISSUE TITLE
Getting null reference error

### ISSUE THREAD

**Issue by mokonta** [qetza/replacetokens-task#65]
I'm using v5 in TFS 2017 release pipeline and I'm getting an error similar to https://github.com/qetza/vsts-replacetokens-task/issues/196

Unable to process command '##vso[task.setvariable variable=tokenReplacedCount;isOutput=false;issecret=false;]1' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)

Value cannot be null. (Parameter 'RefName')

Agent version is 2.165.2

**Comment by mokonta** [comment]
According to this ticket https://github.com/microsoft/azure-pipelines-agent/issues/3284 TFS 2017 doesn't support setVariable.isOutput. Is there any workaround for this?

**Comment by mokonta** [comment]
Hi @qetza. Thought I'd tried that but maybe I just tried v4. v3 works. Thanks.

**Comment by qetza** [comment]
Hi @mokonta,
Output variables were introduced in v4 so if your version of the agent doesn't support output variables you'll have to use v3.
